### ISSUE TITLE
Pat Challenge: Mini-Website Exercise: Create a Multi-Page Website

### ISSUE THREAD

**Issue by PatrickFrankAIU** [azamsharp/web-ft-02-2023#33]
### Mini-Website Exercise: Create a Multi-Page Website

**Objective**: Create a mini-website with four interlinked HTML pages. Utilize classic CSS layout techniques to structure the website. Each page should contain a header with the site title, a navigation menu, a main content area, and a footer. Ensure the navigation menu is consistent across all pages.

---

**Instructions:**

* **Use floats and inline-block** for layout structuring. (Floated text allows image wrap; inline-block to support flexible positioning without a flexbox.)
* Ensure the **navigation menu is clearly visible and functional**, allowing users to click through to the different pages. (Already in template)
* Make each page's **main content area distinct in its content**, demonstrating the purpose of the page. Use images and text as appropriate.
* **Include a footer** with copyright information on each page. (Already in template)
* Develop existing CSS styles and add new ones to create and maintain a visually cohesive design across all pages.

---

### Page Details:

1. **Home Page (index.html)**:

   * Should welcome users and briefly describe the website.

2. **About Page (about.html)**:

   * Provides a detailed description of the website or entity it represents.

3. **Services Page (services.html)**:

   * Lists the services or features offered.

4. **Contact Page (contact.html)**:

   * Contains a simple contact form (form action can be a dummy link) and additional contact information.

---

### Provided Code:

**index.html** (and template for the other pages):

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home | Mini-Website</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Mini-Website</h1>
    </header>
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="services.html">Services</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </nav>
    <main>
        <h2>Welcome to Our Mini-Website</h2>
        <p>This is a simple project to demonstrate basic HTML and CSS skills without using modern layout techniques.</p>
    </main>
    <footer>
        <p>&copy; 2024 Mini-Website</p>
    </footer>
</body>
</html>
```

**style.css**:

```css
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
}
header, footer {
    text-align: center;
    padding: 1em;
    background-color: #f3f3f3;
}
nav ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    background-color: #333;
    overflow: hidden;
}
nav ul li {
    float: left;
}
nav ul li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}
main {
    padding: 20px;
}
```

---

### **Contact Page** (contact.html):

Update the `<title>` to "Contact | Mini-Website" and include the following contact form and additional information in the `<main>` area.

```html
<h2>Contact Us</h2>
<form action="#" method="post">
    <label for="name">Name:</label><br>
    <input type="text" id="name" name="name"><br>
    <label for="email">Email:</label><br>
    <input type="email" id="email" name="email"><br>
    <label for="message">Message:</label><br>
    <textarea id="message" name="message"></textarea><br>
    <input type="submit" value="Submit">
</form>
```

---

### Additional Instructions:

* **About Page (about.html)**: Change the `<title>` tag to "About | Mini-Website" and update the `<main>` content to describe the purpose or background of the website.
* **Services Page (services.html)**: Adjust the `<title>` tag to "Services | Mini-Website" and list the services or features in the `<main>` section.
* **Contact Page (contact.html)**: Update the `<title>` to "Contact | Mini-Website" and include a simple contact form and additional contact information in the `<main>` area.
